<?php

/**
 * Implements hook_field_formatter_info_alter().
 */
function empty_fields_field_formatter_info_alter(&$info) {
  foreach ($info as $formatter_key => &$formatter) {
    $formatter['settings'] += array(
      'display_empty' => '',
      'custom_text' => '',
      'empty_callback' => '',
    );
  }
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function empty_fields_field_formatter_settings_summary_alter(&$summary, $context) {
  $display = $context['instance']['display'][$context['view_mode']];
  $settings = $display['settings'];

  $summary = empty($summary) ? '' : $summary . '<br />';
  $settings += array('display_empty' => '');
  switch ($settings['display_empty']) {
    case 'text':
      $summary .= t('Displays empty field with custom text: %text', array('%text' => $settings['custom_text']));
      break;
    default:
      $summary .= t('Empty field is hidden');
      break;
  }

}

/**
 * Implements hook_field_formatter_settings_form_alter().
 */
function empty_fields_field_formatter_settings_form_alter(&$settings_form, $context) {
  $field = $context['field'];
  $display = $context['instance']['display'][$context['view_mode']];
  $settings = $display['settings'];

  $settings_form['display_empty'] = array(
    '#type' => 'select',
    '#title' => t('Empty display options'),
    '#default_value' => $settings['display_empty'],
    '#options' => array(
      '' => t('Do not display'),
      'text' => t('Display value'),
      'callback' => t('Callback'),
    ),
 	);

  // We can not nest this field, so use a prefix / suffix with padding to help
  // to provide context.
  $settings_form['custom_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Custom value'),
    '#default_value' => $settings['custom_text'],
    '#description' => t('This populates the field with the specificied empty value.'),
    '#states' => array(
      'visible' => array(
        ':input[name="fields[' . $field['field_name'] . '][settings_edit_form][settings][display_empty]"]' => array('value' => 'text'),
      ),
    ),
    '#prefix' => '<div style="padding: 0 2em;">',
    '#suffix' => '</div>',
  );

  $callbacks = empty_fields_get_empty_field_callbacks();
  if (empty($callbacks)) {
    unset($settings_form['display_empty']['#options']['callback']);
  }
  else {
    $options = array();
    foreach ($callbacks as $key => $info) {
      $options[$key] = $info['label'];
    }
    $settings_form['empty_callback'] = array(
      '#type' => 'select',
      '#title' => t('Custom callbacks'),
      '#default_value' => $settings['empty_callback'],
      '#options' => $options,
      '#states' => array(
        'visible' => array(
          ':input[name="fields[' . $field['field_name'] . '][settings_edit_form][settings][display_empty]"]' => array('value' => 'callback'),
        ),
      ),
      '#prefix' => '<div style="padding: 0 2em;">',
      '#suffix' => '</div>',
   	);
  }
}

/**
 * Implements hook_field_attach_view_alter().
 */
function empty_fields_field_attach_view_alter(&$result, $context) {
  if (empty($context['view_mode']) || empty($context['display']) || $context['view_mode'] != $context['display']) {
    return;
  }
  $view_mode = $context['view_mode'];
  $entity_type = $context['entity_type'];
  $entity = $context['entity'];
  $language = $context['language'];
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  $rendered_elements = element_children($result);

  foreach (field_info_instances($entity_type, $bundle) as $field_name => $instance) {
    if (in_array($field_name, $rendered_elements)) {
      continue;
    }
    $field = field_info_field($field_name);

    // Do not add field that is hidden in current display.
    $display = field_get_display($instance, $view_mode, $entity);
    if ($display['type'] == 'hidden' || empty($display['settings']['display_empty'])) {
      continue;
    }

    $markup = '';
    switch ($display['settings']['display_empty']) {
      case 'text':
        $markup = filter_xss_admin($display['settings']['custom_text']);
        break;

      case 'callback':
        if (!empty($display['settings']['empty_callback'])) {
          $callbacks = empty_fields_get_empty_field_callbacks();
          if (!empty($callbacks[$display['settings']['empty_callback']])) {
            $func = $callbacks[$display['settings']['empty_callback']]['callback'];
            if (function_exists($func)) {
              $context['display'] = $display;
              $context['instance'] = $instance;
              $context['field'] = $field;
              $markup = (string) $func($field_name, $context);
            }
          }
        }
        break;

    }

    $result[$field_name] = array(
      '#theme' => 'field',
      '#title' => $instance['label'],
      '#label_display' => $display['label'],
      '#field_type' => $field['type'],
      '#field_name' => $field_name,
      '#bundle' => $bundle,
      '#object' => $entity,
      '#items' => array(
        0 => array('value' => $markup),
      ),
      '#entity_type' => $entity_type,
      '#weight' => $display['weight'],
      0 => array(
        '#markup' => $markup,
      ),
    );
  }
}

/**
 * Get all the empty field callbacks via hook_empty_field_callbacks().
 */
function empty_fields_get_empty_field_callbacks() {
  $info = &drupal_static(__FUNCTION__);

  if (!isset($info)) {
    $cid = "empty_fields:" . $GLOBALS['language']->language;
    if ($cache = cache_get($cid)) {
      $info = $cache->data;
    }
    else {
      $info = module_invoke_all('empty_field_callbacks');
      drupal_alter('empty_field_callbacks', $info);
      cache_set($cid, $info);
    }
  }

  return $info;
}
